//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStroe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDetails
    {
        public string BookName { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> SaleNum { get; set; }
        public Nullable<int> Inventory { get; set; }
        public string Type { get; set; }
        public string Path { get; set; }
    }
}
